### ISSUE TITLE
Level 19 not working right

### ISSUE THREAD

**Issue by sturlath** [flukeout/css-diner#93] opened 2014-08-20 22:50 UTC
The selector is "shaking"/selecting the third plate but it does not finish the level. 
Here is the selector Im using 
div plate:nth-child(3)

**Comment by gangsthub** [comment] 2015-01-04 22:27
`bento:nth-child(2)` worked for me, but not the `nth-last-child(2)` as expected

**Comment by sepulchered** [comment] 2015-01-28 12:14
bento:nth-child(2) worked for me, but not the nth-last-child(2) as expected too

**Comment by sepulchered** [comment] 2015-01-28 12:42
also duplicate of #87

**Comment by flukeout** [comment] 2015-01-28 20:53
@sturlath Wait - level 19 is 'select the 1st bento' - why does the third plate matter, are we talking about the same thing?

**Comment by flukeout** [comment] 2015-01-28 20:54
@sepulchered Hey - so which selector isn't working that should be?

**Comment by sepulchered** [comment] 2015-01-29 04:06
@flukeout no, it's ok with selector there's problem with nth-last-child selector description - everybody seems to expect `bento:nth-last-child(2)` thinking like 'selct second bento from the last element' to be the answer instead of `bento:nth-last-child`

**Comment by flukeout** [comment] 2016-08-03 15:42
Yeah, @sepulchered - this has come up quite a few times. I've added a task to the roadmap to look into how to address this...
- Better rule explanation?
- A special 'hint' for that level if people want it?

...other thoughts?

It's the most misunderstood selector, poor fella.

**Closed by flukeout** 2016-08-03 15:42 UTC

**Comment by ivodimitrov** [comment] 2017-03-12 17:46
bento:nth-last-child(3) 

or

bento:nth-child(2)

**Comment by Michele24** [comment] 2017-06-17 06:07
Not working for me.  I've tried bento:nth-last-child(4) and :nth-last-child(4). The screen just shakes.

**Comment by flukeout** [comment] 2017-06-17 22:55
Hi @Michele24, the answers in the comment above yours should work just fine. 

``:nth-last-child(4)`` selects the 4th child from the end of the elements. Which in the case of the level, is the first plate.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/25212/27256772-63946e9c-5375-11e7-9905-cbad9c92ddbc.png">

**Comment by Michele24** [comment] 2017-06-17 23:41
Thanks for the response; I tried "bento:nth-last-child(3)" and it worked.

**Comment by Michele24** [comment] 2017-06-17 23:42
Thanks - bento:nth-last-child(3) worked.

**Comment by benjifriedman** [comment] 2017-07-04 22:57
` :nth-last-child(4) +` worked for me. Selecting the following element of the first plate.

**Comment by jayfredo** [comment] 2017-11-02 16:06
Okay so I'm still new to CSS and I was wondering this:

Why doesn't bento:nth-last-child(2) work? Doesn't that syntax mean I'm selecting the second to last bento child? bento:nth-last-child(3) seems like it would only work if there were 3 bento children. This level really threw me for a loop.

**Comment by Nmuta** [comment] 2018-09-20 22:32
bento:nth-last-child(3)  works. 

I also agree, this is probably one of the most misunderstood selectors. I think better explanation for students would help a ton with this.

**Comment by DankSteelMemes** [comment] 2019-05-02 00:25
I came here looking for answers because this one really confused me. I too initially thought "bento:nth-last-child(2)" would work. I ended up just throwing numbers at it to finally pass it with the correct command. I am still left confused by this command and the description was not much help.

Thank you for making this though, it is amazing. I do really appreciate the fact that it is available.

**Comment by ui-coder** [comment] 2019-05-04 04:45
Hi there. Try this *bento:nth-last-child(3)*. It works right. Good luck to
you. ;0))

==============
Best regards,
Willie S. Ceres
(@htmlstrap)
------------------------
[image: Picture]

**Comment by obaseotumoyi** [comment] 2019-12-22 20:38
It was difficult, so I quickly started throwing in stuff, and bento:nth-last-child(3) worked, but came here to look for explanations for better understanding, but they seem to be nothing concrete. Guess I have to go to w3c

**Comment by obaseotumoyi** [comment] 2019-12-22 20:39
Holla if you are new, at CSS and passionate about programming and could do with a buddy, I think I need one.

**Comment by rawatdev** [comment] 2022-03-14 14:22
_Solution: bento:nth-last-child(3) is correct one._ 

The :nth-last-child(n) selector matches every element that is the nth child, regardless of type, of its **parent**, counting from the last child. It selects inside the parent. And by saying only :nth-last-child(3) it selects bento and orange. So, we specify it by adding bento to it.
For complete understanding refer [w3schools](https://www.w3schools.com/cssref/sel_nth-last-child.asp)

**Comment by lanaduval** [comment] 2022-07-08 22:50
Omg thanks, I came here bc it was so tricky haha thank you all for the explanation

**Comment by kaushikjainkj** [comment] 2022-09-23 10:16
`bento:nth-child(3`) is the correct answer and it worked!

**Comment by mgmaloney** [comment] 2023-04-11 17:14
I think the explanation isn't very clear when describing what nth-last-child does

":nth-last-child(2) selects all second-to-last child elements."

_second-to-last_  I believe would be the element right next to the last element.
https://en.wiktionary.org/wiki/second_to_last#:~:text=Penultimate%2C%20next%20to%20last%2C%20immediately,of%20a%20sequence%20or%20list.

So because english is confusing, the wording makes most people think that nth-last-child selects in the same way as we speak.  but in reality it selects **nth from the last** instead of **nth to last**

**Comment by PhillJr** [comment] 2024-04-02 00:20
For anyone record using ">:nth-last-child(3)" worked for me
